### ISSUE TITLE
O Projekcie i Aktualności

### ISSUE THREAD

**Issue by bartoszwalacik** [pwd-project/pwd#1]
Jako Projektant serwisu jednostki samorządowej, chcę mieć w internecie serwis prezentujący zasady jakie musi spełniać serwis aby był dostępny dla osób, które ze względu na wiek lub niepełnosprawność są zagrożone wykluczeniem cyfrowym, w jaki sposób będzie to oceniane i mieć tam aktualne informacje na temat rozwoju prac, tak aby odpowiednio przygotować się do pracy zmierzającej do podniesienia dostępności serwisu jakim się opiekuję

Tu bym chciał aby powstał szkielet tak aby można kolejne osoby mogły kodować i zmierza ku makiecie przygotowanej tu:
https://moqups.com/Robert.Smietanka/jLZ0mYZ0/

**Comment by kadamowi** [comment]
Efektem tej historyjki ma być ma być klasyczna strona pod adresem http://pwd-prod.herokuapp.com/
zawierająca: nagłówek, menu, część aktywną i stopkę.
Menu ma być: "Aktualności" i "O projekcie" (potem dojdą jeszcze 3 lub 4 pozycje).
W części aktywnej pod tymi dwoma menu będą statyczne strony.
Na ten release wystarczy jak to będą pliki na GitHub z treścią w formacie HTML.
