### ISSUE TITLE
google a11y not appliable

### ISSUE THREAD

**Issue by bgalek** [pwd-project/pwd#109]

**Comment by smikulsk** [comment]
@kadamowi Co ma się dziać w przypadku, gdy metryka jest not applicable? Ma się nie liczyć do score, czy score ma być równe 100 doda tej metryki?

-----Wiadomość oryginalna-----
Od: "Bartosz Gałek" <notifications@github.com>
Wysłano: ‎2015-‎10-‎26 22:19
Do: "pwd-project/pwd" <pwd@noreply.github.com>
Temat: [pwd] google a11y not appliable (#109)
