### ISSUE TITLE
PWD API - Globalny wskaźnik

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#111]
Przekazanie na zewnąrz wskaźnika np: 
pwd.dolinagubra.pl/api=gwd
Coś w tym stylu.
Wersja trudniejsza wskaźnik dla strony z podaniem url-a

**Comment by bgalek** [comment]
pwd.dolinagubra.pl/api/gwd
pwd.dolinagubra.pl/api/gwd/google.pl/
pwd.dolinagubra.pl/api/gwd/xyz.pl/
