### ISSUE TITLE
Zbadanie błędu na wzp.pl

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#112]
Szczegółowe zbadanie przypadku http://wzp.pl/
Kiedyś przeszło (3 października) i dostało dobry wyni 69.
Aktualnie regularnie dostaje 0 z responsem 408 (niby timeout ale wynik jest po ułamku sekundy)

Zauważyłem przypadek takO
krok 1)  puszczam z rula - wynik 0
krok 2) robię "odśwież" - wynik poprawny

**Comment by kadamowi** [comment]
Zauważyłem jedną rzecz, jeszcze próbowałem zbadać to na https://validator.w3.org/
Wynik:
Sorry! This document cannot be checked.
500 Can't connect to sso.wzp.pl:443
If you made recent changes to your domain name (DNS) configuration, you may also want to check that your domain records are correct, or ask your hosting company to do so.

**Comment by kadamowi** [comment]
Ale ten już przechodzi, ciekawe czym się różnią
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwzp.pl

**Comment by bgalek** [comment]
https://pwd-analysis.herokuapp.com/analysis?url=wzp.pl = przekierowanko
https://pwd-analysis.herokuapp.com/analysis?url=http://wzp.pl = poprawny adres, to nie o to chodzi?
