### ISSUE TITLE
Metryka alt - wyjaśnienie błędów testera

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#119]
https://docs.google.com/spreadsheets/d/1_ibTEdZpNIya4QzPemVhXiQZkZGEDzqTb7IzElOcV4s/edit#gid=604684329

**Comment by bgalek** [comment]
to bedziesz musial mi bardziej opisac bo nie rozumiem z tego nic

2015-10-29 0:08 GMT+01:00 Krzysztof Adamowicz <notifications@github.com>:
