### ISSUE TITLE
Kontakt - strona kontaktowa (w layoucie)

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#13]
Jako Użytkownik PWD, chcę mieć możliwość kontaktu za pośrednictwem strony w celu zadania pytania na dowolny temat, tak aby na bieżąco zgłaszać wszelkie wątpliwości dotyczące oceny dostępności

**Comment by kadamowi** [comment]
Nowa pozycja w menu z #1 o nazwie "Kontakt"
Ma być tam prosty formularz z polami:
Imię, Nazwisko, email, - wymagane
url - strona jakiej dotyczy pytanie, ,może być puste
nr telefonu - może być puste
Pytanie - treść pytania, minimum 10 znaków
Po submit wysyłamy maila na adres jaki sobie utworzymy, zawierający powyższe dane.
i wrzucamy komunikat jaki sobie określimy typu "pytanie przyjęte odpowiemy w najbliższym czasie"

**Comment by kadamowi** [comment]
Na obecnym etapie niech to będzie email na skrzynkę kontakt@pwd.dolinagubra.pl
Czy coś wpadło można podglądać na https://poczta.home.pl
Hasło:PWDkontakt2015

**Comment by bgalek** [comment]
Krzysiek podałeś hasło na githubie :) przyślij mi nowe hasło na maila :)

**Comment by kadamowi** [comment]
Kotek2015

Myślałam,  że tylko kod jest public 😊
24 sie 2015 09:54 "Bartosz Gałek" <notifications@github.com> napisał(a):

**Comment by bgalek** [comment]
Krzysiek, odpisałeś na githuba (dodając tym samym komentarz :D)

**Comment by kadamowi** [comment]
OK, zaraz wyślę ;-)
