### ISSUE TITLE
Analiza 5 stron, których nigdy silnik nie zrobił

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#130]
207011;"Urząd Miasta Kamienna Góra";"http://www.kamiennagora.pl/"
217000;"Starostwo Powiatowe w Strzelinie";"http://www.powiatstrzelinski.pl"
217032;"Urząd Gminy Przeworno";"http://www.przeworno.pl"
217043;"Urząd Miasta i Gminy w Strzelinie";"http://www.strzelin.pl"
218012;"Urząd Gminy Kostomłoty";"http://www.kostomloty.pl"

**Comment by bgalek** [comment]
2015-11-09T02:01:47 [DEBUG] Network - Resource request error: 5 ( "Operation canceled" ) URL: "http://www.kamiennagora.pl/"
https://github.com/ariya/phantomjs/issues/12750

wszystkie strony cierpia na to samo, wygladaja podobnie i wszystkei maja flasha, wyglada ze to jest problem. rozwiazanie jest proste: pwd-analysis podejmie 3 proby zanim zwroci wynik, (jesli dostanie status "Fail" od razu przy (Resource request error: 5))
