### ISSUE TITLE
Metryka - w3.org walidator

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#155]
Uruchamiamy 
https://validator.w3.org/nu/?doc=http://dolinagubra.pl/
i analizujemy div z result badamy
Bazowe jest 100pkt
za każdy error fatal -5
za każdy error -1
za każdy warning -0.1
score - MAX(0,wynik)

**Comment by bgalek** [comment]
myslalem o tym dzisiaj, w3c nie ma wplywu na dostepnosc, czemu mamy to badac?:)

**Comment by kadamowi** [comment]
Jest to jedna z metryk WCAG 4.1.1
http://fdc.org.pl/wcag2/#ensure-compat
i jest przez Widzialnych sugerowana
http://wcag20.widzialni.org/parsowanie,new,mg,168,180.html.html,115

A wydaje mi się, że w miarę prosta w implementacji.

KA



2015-11-23 18:13 GMT+01:00 Bartosz Gałek <notifications@github.com>:

**Comment by kadamowi** [comment]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fpwd.dolinagubra.pl%2F
Tu jesteśmy 100%
i ten bym wrzucił.

Natemiast ten drugi z widzialnych
http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fpwd.dolinagubra.pl%2F&profile=css3&usermedium=all&warning=1&vextwarning=&lang=pl-PL
to już jakaś masakra jest, nie wiem czy tak źle u nas jest, czy coś
przesadza.



W dniu 23 listopada 2015 20:20 użytkownik Krzysztof Adamowicz <
kadamowi@gmail.com> napisał:
