### ISSUE TITLE
Status silnika

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#16]
Jako Administrator PWD, chcę chcę mieć możliwość podglądania na ukrytej stronie statusu działania audytu (czy działa, ilość błędów), tak aby monitorować działanie i na bieżąco reagować gdy pojawiają się błędy

**Comment by kadamowi** [comment]
To jest chyba to co mamy w "Wyniki analizy" tylko będzie (w sumie już jest) dostępne jako http://pwd-prod.herokuapp.com/audyty

**Comment by bartoszwalacik** [comment]
nazwa 'status silnika' brzmi nieco kryptycznie ... to może zmieńmy nazwę tej historyjki?

btw. potrzebujey historyjki na security do klikania w ten button RunAudit i w ogóle do ekranu z listą audytów ...

**Comment by kadamowi** [comment]
Zakładałem pierwotnie, że RunAudit uruchamia się automatycznie raz w tygodniu o określonej porze, Przycisk będzie tylko na czas developmentu gdy będziemy chcieli sobie to puszczać częściej, a napewno po wdrożeniach. Ekran z listą jak będzie pod linkiem to dla mnie ok.

Zostawiam to do decyzji, jeśli to temat prosty to róbmy jak nie to na razie odkładamy.

**Comment by bartoszwalacik** [comment]
ok, to taka strona jest zrobiona, więc może zamkniemy tą historyjkę i wrzucimy nową na zastąpienie buttona przez scheduler?

**Comment by kadamowi** [comment]
OK
