### ISSUE TITLE
Metryka 1.3.1 - Gęstość tagów formatujących

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#17]
Zidentyfikować wszystkie tagi formatujące:
```
<b>, <strong>, <font>, <i> <br>, <u>, &nbsp; <color>,  <center>, <left>, ...
```
Policzyć ratio ilości tagów formatujących do wszystkich, wynik odwrócić (i ew. przeskalować).

Uzasadnenie: dobry dokument html powinien zawierać tylko tagi strukturalne i semantyczne
(takie jak `<h1>, <section>, <p>, <label>`)

**Comment by kadamowi** [comment]
Treść na stronie internetowej jest podstawowym sposobem przekazywania informacji. Należy zadbać o to, aby użyte w nim znaczniki HTML zapewniły jego logiczną strukturę. W dalszym ciągu zdarza się, że twórcy stron internetowych używają znaczników niezgodnie z ich przeznaczeniem. Dla nich jest bez różnicy, czy wykorzystują znacznik <b>,  <strong>, <font size=”14pt”>  czy <h1>. Przecież i tak się w CSS zmieni wygląd. Niestety, robią podstawowy błąd.
W języku HTML znaczniki możemy podzielić na dwie podstawowe kategorie:
znaczniki formatujące – ich zadaniem jest zmiana wyglądu tekstu: pogrubienie  <b>, pochylenie <i>, podkreślenie <u> . Znaczniki te powinny być wykorzystywane tylko w celach poprawienia estetyki, a nie po to, by zaznaczyć ważną informację. Najlepiej jednak w ogóle ich nie używać. Formatowanie zostawić po stronie CSS.

znaczniki semantyczne – ich zadaniem jest określenie znaczenia danego fragmentu tekstu: nagłówek – <h1>, <h2>; mocne wyróżnienie – <strong>; zmiany – <ins>,<del>;  tabela –  <table>; tytuł tabeli - <caption>, etykieta - <label>. Sposób, w jaki treści zostaną przedstawione zależy od  klienta http, np. słowo do którego dodany jest znacznik  <acronym>  w MS Internet Explorer domyślnie zostaje podkreślone linią przerywaną, natomiast w FireFoxie linią kropkowaną. Słowo ze znacznikiem <strong> w przeglądarce MS Internet Exploer, Firefox, Opera będzie pogrubione, natomiast w przeglądarce tekstowej Lynx zostanie ono przedstawione w innym kolorze.
Podczas budowy strony internetowej należy zwrócić szczególną uwagę na zastosowanie znaczników semantycznych. Dzięki nim programy czytające (screen readers), używane przez osoby niewidome i niedowidzące, mogą w prawidłowy sposób zinterpretować i odczytać treść strony. Użytkownicy niewidomi wykorzystują większość klawiszy jako skróty klawiaturowe oraz dużą ilość ich kombinacji, interpretowanych przez programy czytające do nawigacji po stronie internetowej. Skróty różnią się w zależności od producenta oprogramowania.
Przykład:
klawisz „H” - będzie służył do poruszania się tylko po nagłówkach strony internetowej,
klawisz „L” - przechodzenia pomiędzy listami,
klawisz „G” – przejścia do grafiki,
klawisz „F” – przejścia do pola formularza.
Musimy wiedzieć, że taki program czytający nie służy tylko do obsługi strony internetowej, ale całego systemu i aplikacji zainstalowanych na komputerze.
Oczywiście, aplikacje przeznaczone dla osób z dysfunkcjami to nie jedyne oprogramowanie, dla którego znaczniki semantyczne mają znaczenie. Nie możemy zapomnieć o dziesiątkach robotów wyszukiwarek (np. google, bing), które codziennie odwiedzają nasz serwis. Dla nich nie bez znaczenia jest to, czy do zdefiniowania nagłówka artykułu lub produktu w sklepie użyto znacznika <font size=”14pt”> czy  <h1>. W dużym uproszczeniu, roboty nie rozróżniają wielkości czcionki, natomiast sprawdzają, czy treść jest nagłówkiem <h1>, czy też zwykłym akapitem tekstu <p>. Jeżeli wykorzystamy odpowiednie znaczniki, wtedy robot lepiej zaindeksuje naszą stronę w wyszukiwarce a program czytający pozwoli użytkownikom niewidomym na rozpoznanie struktury serwisu i przemieszczanie się po jego istotnych elementach. Same korzyści!

**Comment by smikulsk** [comment]
Jako tagi formatujące zidentyfikowano następujące:
abbr,acronym,address,article,b,basefont,bdi,bdo,big,blockquote,br,center,cite,code,del,details,dfn,dialog,em,figcaption,figure,font,hr,i,ins,kbd,mark,meter,pre,q,rt,s,samp,small,strike,strong,sub,sup,time,u,wbr
oraz tagi zawierające atrybut align
