### ISSUE TITLE
Zbiór serwisów

### ISSUE THREAD

**Issue by bartoszwalacik** [pwd-project/pwd#2]
Jako Administrator PWD, chcę chcę mieć możliwość inicjalnego załadowania około 3000 stron serwisów jednostek samorządowych z podstawową informacją o nich i modyfikowania tej listy w przyszłości, tak aby utworzyć zbiór serwisów jakie będą regularnie analizowane

**Comment by bartoszwalacik** [comment]
W ramach tego taska załadowana do pwd-service zostanie lista kilkunastu przykładowych stron.
Lista będzie wystawiona po REST pod adresem /api/websites

**Comment by kadamowi** [comment]
Obiekt strona powinie zawierać takie informacje:
Kod jednostki (może być pusty) - unikalny identyfikator jednostki, jak będzimy chcieli zaktualizować informacje to po tym kodzie.
Województwo, Powiat, Miasto - potrzebne w #8 do wyszukiwania konkretnej strony
Typ - to będzie krótki słownik typu: Gmina, Powiat, ... potrzebne do #11 
Nazwa - nazwa strony będzie wykorzystywana do wyświetlania w #8 i do metryki #3 
URL - wiadomo
Email - adres mailowy jednostki, po ten adres będziemy wysyłać automatyczne maile z #14 
Stanowisko, Imię, Nazwisko - osoba kierująca stroną urzędu, będzie potrzebne do nagłówka #14

**Comment by kadamowi** [comment]
Wrzuciłem całe województwo mazowieckie
