### ISSUE TITLE
Metryka 2.4.10 - Nawigacja - Nagłówki sekcji

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#23]
Sprawdzenie, czy każda z sekcji z treścią jest opisana za pomocą nagłówków (tytułów), tam gdzie będzie to konieczne. 

Jeśli na stronie nie ma tagów to metryka daje wartość N/A (null)

Sprawdzamy warunki:
- każdy tag  `<h>` musi być niepusty
- powinien być 1 tag `<h1>` i powinien być pierwszy
- tagi `<h>` nie powinny występować bezpośrednio po sobie, liczone jako stosunek ilości tagów h po których następny tag to też tag h do ilości wszystkich tagów h
- tagi `<h>` powinny zawierać tylko tekst, nie mogą zawierać innych tagów

**Comment by bgalek** [comment]
po kazdym h1,h2,h3... ma być blok testu, a nie w srodku taga
