### ISSUE TITLE
Metryka 3.1.1 - Czytelność - Język strony

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#24]
Sprawdzenie, czy został określony główny język strony za pomocą atrybutu lang i/lub xml:lang w znaczniku HTML. 

Bartosz Gałek  sprawdzenie tagu html i porownanie jego atrybutów

**Comment by kadamowi** [comment]
Sprawdziłem 1000 stron z naszej bazy.
506 - brak 
200 - pl
97 - pl ale brak dla xml:lang
165 - pl-pl
21 - pl-pl brak dla xml:lang
pozostałe to np: en, en-gb, pol-PL
Nie wiem czy wszystkie są poprawne, proponuję poprawny 100% nie 0%

**Comment by bgalek** [comment]
html lang u xml:lang to powinny byc dwie metryki. html lang dotyczy calego drzewa DOM a xml:lang moze dotyczyc poszczegolnch wezlow

**Comment by bgalek** [comment]
a co do poprawności, pl i pl-pl jest poprawne, zakladalbym brak - 0, jakikolwiek - 100, poprawnosc wartosci mozna wyciagnac z analizy zgodnosci z w3c

**Comment by kadamowi** [comment]
Czy <meta name="language" content="en" /> jest poprawne ?
Bo http://www.brudzen.pl/ niema lang daliśmy jej 0, ale ma to coś powyżej, ale i tak jest niepoprawnie bo wskazuje na en a strona jest po polsku.
