### ISSUE TITLE
Metryka 3.3.2 - Pomoc - Etykiety lub instrukcje

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#26]
Sprawdzenie, czy w każdym miejscu, w którym wymagane jest wprowadzenie przez użytkownika informacji zostały zapewnione czytelne etykiety lub instrukcje czy przykłady.

**Comment by bgalek** [comment]
sprawdzenie czy kazdy element input ma przyciagniety label

**Comment by smikulsk** [comment]
metryka AX_TEXT_01 z a11y
