### ISSUE TITLE
Metryka 2.4.2 - Nawigacja - Tytuł strony

### ISSUE THREAD

**Issue by bartoszwalacik** [pwd-project/pwd#3]
Sprawdzenie, czy strona internetowa ma tytuł opisowy i informacyjny mówiący o niej.
1) Analizujemy czy występuje <title></title>
brak - 0
jest analizujemy dalej
2) Analizujemy w prosty sposób zawartość tag-a jak zawiera miasto jakie mamy na liście to 100%
Przykład: Urząd Miejski w Bytomiu Odrzańskim - http://www.bytomodrzanski.pl/ <title>Bytom Odrzański - Home</title>
3) Czy title zawiera słowo kluczowe z listy (Aktualności, Strona główna, ...)
http://www.chelm.pl/ - Aktualności - 50% 
4) pozostałe 10% np: http://www.miedzyrzecgmina.pl/ - tylko słowo Gmina

**Comment by kadamowi** [comment]
Trzeba uwarzać na:
1) www.bobrowo.samorzad.org.pl
Jak się za szybko bobierze html to mamy title "Your Page Title"
który kwalifikuje się na 10%
po chwili jednak następuje przekierowanie na http://www.bobrowo.org.pl
i tam title jest już "Aktualności - Oficjalna strona internetowa Gminy Bobrowo"
który kwalifikujemy na 100%
Ma być 100%
2) www.jeziorawielkie.pl
Na moim harvesterze wyskakuje jakieś info o wtyczce i czeka na ręczny klik
3) www.jeziorawielkie.pl
Podstrona która każe wybrać język.
Chyba pójdziemy po najmniejszej linii oporu i w bazie zarejestrujemy
www.jeziorawielkie.pl/polski.htm

**Comment by bgalek** [comment]
curl  https://pwd-analysis.herokuapp.com/analysis/\?url=http://www.radom.pl

**Comment by bgalek** [comment]
albo bez curla w zasadzie https://pwd-analysis.herokuapp.com/analysis?url=http://www.javers.org redirecty wykryje drugi endpoint https://pwd-analysis.herokuapp.com/metrics?url=http://www.bobrowo.samorzad.org.pl - on tez pokazuje ile jest redirecotow i gdzie prowadza
