### ISSUE TITLE
Metryka 4.1.1 - poprawność htmla strony

### ISSUE THREAD

**Issue by bgalek** [pwd-project/pwd#34]
metryka zgodna z w3c vaidaor

**Comment by bgalek** [comment]
https://pwd-analysis.herokuapp.com/validate?url=http://www.bobrowo.org.pl/asp/pl_start.asp

**Comment by kadamowi** [comment]
To chyba pokrywa się z #24 ... tak ?

**Comment by bgalek** [comment]
tak :)
