### ISSUE TITLE
Metryka - Pytanie o Cookies

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#39]
Przykładowa strona to http://gmina-miedzna.pl/
Jest tam dość bezczelna interpretacja wymogu pytania o cookie, gdzie harvester się na nim zacina.
Zleciłem człowiekowi zbadania czy readery sobie z tym radzą i jak nie: to dostaje z marszu 0% jak teraz i nie tykamy. Jak sobie radzą to trzeba będzie przez to przejść.
Brak cookies lub ciężko zamykalne - 100

**Comment by bgalek** [comment]
nie da się powiedzieć "ciężkie zamykanie" - jak to zbadać?
