### ISSUE TITLE
Metryka 1.1.1 - Tekst alternatywny

### ISSUE THREAD

**Issue by bartoszwalacik** [pwd-project/pwd#4]
Tekst alternatywny: zapewnij tekst alternatywny dla każdej informacji nietekstowej, aby przyjął formę zrozumiałą 

Metryka licząca czy obiekty graficzne mają tekst pod tagiem alt

Wejście - url
wyjście: score [0,100]

100 jeśli wszystkie obiekty mają alt, 0 jeśli żaden

**Comment by kadamowi** [comment]
Proponuję:
1) Nie dyskretnie tylko liniowo czyli score = 100*<liczba obiektów z niepustym alt>/<liczba wszystkich obiektów>
2) Analizujemy na tym etapie tylko: <img>, <input> i <area>

**Comment by bgalek** [comment]
curl  https://pwd-analysis.herokuapp.com/analysis/\?url=http://www.radom.pl

**Comment by bgalek** [comment]
input i area to inna metryka dotyczaca formularzy
