### ISSUE TITLE
Metryki - metadane

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#43]
Dodanie do metryki po stronie analysys 3 informacji:
*status*
DISABLED - metryka wogóle nic nie liczy i nie jest wyrzucana na Raport
ENABLED - metryka się liczy 

*weight*
liczba 0-100 oznaczające wagę metryki

*order*
(int) na bazie tej liczby będą sortowane na prezentacji

Analysys będzie te dane zwracał w response i po stronie PWD trzeba uwzględnić wyniki

**Comment by bartoszwalacik** [comment]
proponuję to zrobić jednak w całości po stronie pwd-service i nie zmieniać pwd-analysis.
Będziemy wtedy mogli np pokazać wagi i inne metadane na stronkach metryk.

Po dodaniu nowej metryki w analysis i tak trzeba będzie zrobić jej stronkę w pwd, więc nie unikniemy couplingu pomiędzy 2 usługami
