### ISSUE TITLE
Metryki - Sprawdzenie czy strona używa popularnych CMS

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#48]
Sprawdzamy <meta generator i czy zawrta tam informacja zawiera ślady po: Joomla, WordPress i Drupal

**Comment by bgalek** [comment]
A czemu to miałoby obniżać nasza ocene? Chyba nieistotny jest silnik
strony!
29 sie 2015 16:37 "Krzysztof Adamowicz" <notifications@github.com>
napisał(a):

**Comment by kadamowi** [comment]
To tylko informacyjnie, metryka będzie z wagą 0.
29 sie 2015 19:01 "Bartosz Gałek" <notifications@github.com> napisał(a):

**Comment by bgalek** [comment]
Ok, nadal, co ta informacja za sobą niesie? :) moim zdaniem zbedna
29 sie 2015 19:11 "Krzysztof Adamowicz" <notifications@github.com>
napisał(a):
