### ISSUE TITLE
Lista metryk

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#7]
Strona statyczna "Metryki" z listą metryk, każda metryka linkuje do podstorny.

urle:
```
/metryki
/metryki/anyTitle
...
```

gdzie jest opis 'biznesowy" jak działa algorytm.
Uzupełnienie przykładowych docy dla 3 metryk

**Comment by bartoszwalacik** [comment]
struktura stron zrobiona, uzupełniłem opis dla metryki alt, pozostałe do uzupełnienia
