### ISSUE TITLE
Strona Kontakt

### ISSUE THREAD

**Issue by kadamowi** [pwd-project/pwd#98]
Kilka zmian:
- zdjęcie walidacji z adresu strony
- wprowadzanie zabezpieczenia przed bot-ami (propozycja padła aby wstawić nowe pole np: telefon, zrobić je kolorystycznie niewidoczne  i przy submicie sprawdzać czy jest wypełnione)
- przy wysyłce maila zapisać w bazie w nowej tabeli zawartość formularza.

**Comment by bgalek** [comment]
Ad.2 łeee słabo ;) lepiej - https://www.google.com/recaptcha/intro/index.html

**Comment by bgalek** [comment]
omg, a czemu zapisujemy wysylanego maila?
